import React,{useState} from 'react';
import * as I from 'lucide-react';
import {today,fmtDate,money} from '../utils/format.js';
import {isActive as active,all} from '../db.js';
import {renderTemplate,DEFAULT_TEMPLATES} from '../services/whatsapp/templates.js';
import {evaluateRules} from '../engines/notifications/rules.js';
import {Screen,Section,Card,Row,Stat,Badge,Empty} from '../components/ui.jsx';

export function Finance(p){const [period,setPeriod]=useState('month');const prefix=period==='month'?today().slice(0,7):period==='year'?today().slice(0,4):'';const studentIds=new Set(p.students.map(s=>s.id));const payments=p.data.payments.filter(x=>active(x)&&studentIds.has(x.studentId)&&(!prefix||String(x.date||'').startsWith(prefix)));const expenses=p.data.expenses.filter(x=>active(x)&&(!p.yearId||x.academicYearId===p.yearId)&&(!prefix||String(x.date||'').startsWith(prefix))&&(!p.branchId||p.branchId==='ALL'||x.branchId===p.branchId));const revenue=payments.filter(x=>x.type==='PAYMENT').reduce((a,x)=>a+Number(x.amount||0),0),cost=expenses.reduce((a,x)=>a+Number(x.amount||0),0),overdue=p.students.reduce((a,s)=>a+p.due(s),0);return <Screen title="المالية" action={<div className="actions"><button className="btn" onClick={()=>p.setModal('payment')}><I.Plus/> دفعة</button><button className="btn secondary" onClick={()=>p.setModal('expense')}>مصروف</button></div>}><div className="filters"><select className="input" value={period} onChange={e=>setPeriod(e.target.value)}><option value="month">هذا الشهر</option><option value="year">هذه السنة</option><option value="all">كل الوقت</option></select><button className="btn secondary" onClick={()=>p.exportXlsx(`GENIUS_FINANCE_${today()}.xlsx`,{الدفعات:[['التاريخ','الطالب','النوع','المبلغ','الطريقة'],...payments.map(x=>[x.date,p.studentBy(x.studentId)?.name||'',x.type,x.amount,x.method||''])],المصروفات:[['التاريخ','البند','المبلغ'],...expenses.map(x=>[x.date,x.title,x.amount])]})}>Excel</button></div><div className="stats"><Stat n={money(revenue)} l="المدفوع"/><Stat n={money(overdue)} l="المتأخرات"/><Stat n={money(cost)} l="المصروفات"/><Stat n={money(revenue-cost)} l="صافي الدخل"/></div><Section title="كشف حساب الطلاب"><div className="list">{p.students.filter(s=>p.due(s)>0||payments.some(x=>x.studentId===s.id)).map(s=><Card key={s.id}><div className="between"><div><h3>{s.name}</h3><small>{p.groupBy(s.groupId)?.name||''}</small></div><b>{money(p.due(s))}</b></div><div className="actions"><button className="btn secondary" onClick={()=>{p.setSelected(s);p.setModal('studentView')}}>كشف الحساب</button><button className="btn" onClick={()=>p.whatsapp(s.parentPhone,renderTemplate(p.settings.templates?.payment||DEFAULT_TEMPLATES.payment,{studentName:s.name,amount:money(p.due(s)),group:p.groupBy(s.groupId)?.name||''}))}>تذكير WhatsApp</button></div></Card>)}</div></Section><Section title="حركة اليوم"><div className="list">{payments.slice(-15).reverse().map(x=><Row key={x.id} title={`${p.studentBy(x.studentId)?.name||'—'} • ${x.type}`} sub={`${fmtDate(x.date)} • ${money(x.amount)}`}/>)}</div></Section></Screen>}

export function Reports(p){const [type,setType]=useState('students');const [branch,setBranch]=useState('ALL');const [from,setFrom]=useState('');const [to,setTo]=useState('');const inRange=x=>(!from||String(x.date||'')>=from)&&(!to||String(x.date||'')<=to);const branchStudents=p.students.filter(s=>branch==='ALL'||s.branchId===branch);const build=()=>{if(type==='students')return [['الطالب','ID','المجموعة','الحضور','المتوسط','المتبقي'],...branchStudents.map(s=>[s.name,s.code,p.groupBy(s.groupId)?.name||'',p.attendanceRate(s)+'%',p.avg(s)+'%',p.due(s)])];if(type==='finance'){const ids=new Set(branchStudents.map(s=>s.id));return [['التاريخ','النوع','الطالب/البند','المبلغ'],...p.data.payments.filter(x=>active(x)&&ids.has(x.studentId)&&inRange(x)).map(x=>[x.date,x.type,p.studentBy(x.studentId)?.name||x.note||'',x.amount]),...p.data.expenses.filter(x=>active(x)&&(!p.yearId||x.academicYearId===p.yearId)&&(!p.branchId||p.branchId==='ALL'||x.branchId===p.branchId)&&inRange(x)).map(x=>[x.date,'EXPENSE',x.title,x.amount])];}if(type==='groups')return [['المجموعة','الفرع','الطلاب','السعر'],...p.groups.map(g=>[g.name,p.data.branches.find(b=>b.id===g.branchId)?.name||'',p.students.filter(s=>s.groupId===g.id).length,g.price])];return [['الطالب','الحضور','المتوسط','المتبقي'],...branchStudents.map(s=>[s.name,p.attendanceRate(s)+'%',p.avg(s)+'%',p.due(s)])]};const whatsappSummary=`GENIUS ADMIN — تقرير ${type==='students'?'الطلاب':type==='finance'?'المالية':'المجموعات'}\nالفترة: ${from||'البداية'} → ${to||'اليوم'}\nعدد الطلاب: ${branchStudents.length}\nإجمالي المتأخرات: ${money(branchStudents.reduce((a,s)=>a+p.due(s),0))}`;return <Screen title="التقارير" action={<div className="actions"><button className="btn" onClick={()=>p.exportXlsx(`GENIUS_REPORT_${today()}.xlsx`,{تقرير:build()})}>Excel</button><button className="btn secondary" onClick={()=>p.whatsapp(p.settings.phone,whatsappSummary)}>WhatsApp</button><button className="btn secondary" onClick={()=>{navigator.clipboard?.writeText(whatsappSummary);p.notify('تم نسخ التقرير')}}>نسخ</button><button className="btn secondary" onClick={()=>window.print()}>PDF / طباعة</button></div>}><div className="filters"><select className="input" value={type} onChange={e=>setType(e.target.value)}><option value="students">طلاب</option><option value="groups">مجموعات</option><option value="finance">مالية</option><option value="attendance">حضور</option></select><select className="input" value={branch} onChange={e=>setBranch(e.target.value)}><option value="ALL">كل الفروع</option>{p.data.branches.filter(active).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><input className="input" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input className="input" type="date" value={to} onChange={e=>setTo(e.target.value)}/></div><div className="tableWrap"><table><tbody>{build().map((r,i)=><tr key={i}>{r.map((c,j)=>i===0?<th key={j}>{c}</th>:<td key={j}>{c}</td>)}</tr>)}</tbody></table></div></Screen>} }

export function Notifications(p){const ruleCount=evaluateRules(p.data).length;const list=p.data.notifications.filter(active).sort((a,b)=>new Date(b.at)-new Date(a.at));return <Screen title="الإشعارات"><div className="stats"><Stat n={ruleCount} l="قواعد تحتاج متابعة"/><Stat n={list.filter(n=>!n.read).length} l="غير مقروء"/></div><div className="list">{list.map(n=><Card key={n.id} onClick={()=>p.write('notifications',{...n,read:true},'قراءة إشعار')}><div className="between"><div><h3>{n.title}</h3><p>{n.body}</p><small>{new Date(n.at).toLocaleString('ar-EG')}</small></div>{!n.read&&<Badge t="جديد"/>}</div></Card>)}{!list.length&&<Empty text="لا توجد إشعارات"/>}</div></Screen>}


export function Activity(p){const list=[...p.data.activities].sort((a,b)=>new Date(b.at)-new Date(a.at)).slice(0,100);return <Screen title="سجل العمليات"><div className="list">{list.map(a=><Row key={a.id} title={a.action} sub={`${new Date(a.at).toLocaleString('ar-EG')} • ${a.refId||''}`}/>)}</div></Screen>}

